### PR TITLE
logged in status and logout button

### PR DESCRIPTION
**Pull request by fostimus**

### CODE REVIEW

**Comment by fostimus** [comment]
Styling needs work, but functionality works.

**Comment by fostimus** [comment]
@sabre1041 can you do a screen recording of what's happening? I can't reproduce #1, for me whenever I log in I get redirected to the registration page.

For #2, what is not fixed with "Logged in as" specifically? For the moving down park, it is currently on a separate line from the Nav Items -- I need to change the styling, but it should look like this:
Screen Shot 2020-07-27 at 10 30 52 AM

**Comment by sabre1041** [comment]
A few follow ups.

1. Does not work at all on Chrome Incognito. Authentication does not appear to stick after logging in
2. See screenshots for issues experienced (chrome not using incognito)

Screen Shot 2020-07-27 at 5 14 01 PM
Screen Shot 2020-07-27 at 5 14 12 PM

**Comment by fostimus** [comment]
@sabre1041 made some changes, most notably preventing the user from seeing the login button if they are already logged in.

I also changed the RH logo link to redirect to the home page, which right now is 1) login page if not logged in or 2) registration paged if already logged in.

For incognito, we will have to do some redesigning of the auth flow. @AdlerFleurant will have to be involved and do some server side authentication, instead of doing the auth from the frontend and passing the token to the backend.

**Comment by sabre1041** [comment]
@fostimus still seeing issues when logging in where you need to refresh the page after authenticating

**Comment by fostimus** [comment]
@sabre1041 you need to refresh because the API isn't set up yet to handle the data from Google. I pushed another change to redirect on all errors, so you shouldn't see this any more for this pull request

**Pull request merged**
