### PR TITLE
line manager reports update

### PR DESCRIPTION
**Pull request by matallen**
added filters to existing events screen for users, line managers, events a specific number of days old etc..

### CODE REVIEW

**Comment by matallen** [comment]
This feature enhances the events page in the admin console to include user, line manager and event filtering. It also includes exports of the filtered lists, so you can export a report for a specific line manager of their reports' points

**Comment by sabre1041** [comment]
@matallen experiencing testing failures

```
2022-05-05 00:57:27 INFO  Config:101 - Config loading (location=/Users/ablock/Projects/RHC/internal/cop/git/ninja-board/target/ninja-persistence/config.json, size=2360)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.579 sec <<< FAILURE!
testGetEventsV2_30DaysOld(com.redhat.sso.ninja.controllers.EventsControllerTest)  Time elapsed: 0.529 sec  <<< ERROR!
java.lang.NullPointerException
	at java.base/java.util.Hashtable.put(Hashtable.java:475)
	at com.redhat.sso.ninja.user.UserService.search(UserService.java:36)
	at com.redhat.sso.ninja.user.CachedUserService.search(CachedUserService.java:19)
	at com.redhat.sso.ninja.controllers.EventsController.getFilteredEvents2(EventsController.java:274)
	at com.redhat.sso.ninja.controllers.EventsController.getEventsV2(EventsController.java:94)
	at com.redhat.sso.ninja.controllers.EventsControllerTest.testGetEventsV2_30DaysOld(EventsControllerTest.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error: 
  testGetEventsV2_30DaysOld(com.redhat.sso.ninja.controllers.EventsControllerTest)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by matallen** [comment]
that's likely because you were not on the vpn or the "USERS_LDAP_PROVIDER" property was not set up. That test accesses ldap

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
