### PR TITLE
Migration to log4j2

### PR DESCRIPTION
**Pull request by dobozysaurus**
Replace log4j with log4j2, since log4j was EOL'ed back in 2015 (https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces). Log4j2 comes with perf improvements, logback style parameterized logging, and a few other nice features.

### CODE REVIEW

**Comment by sabre1041** [comment]
@matallen can you review?

**Comment by matallen** [comment]
@dobozysaurus The code that's changing from log4j 1.x to 2.x is fine, no worries there. However I'm afraid I'm going to reject this PR based on the 180+ lines changed for unnecessary reformatting & import shuffling.  I'm grateful getting contributions, however try to make just the necessary changes for the functionality change. To move forward, I'm happy to create new PR with just your log4j2 changes, or else I'm happy for you to do that.

**Comment by dobozysaurus** [comment]
@matallen No problem; PR with only log4j2 changes incoming shortly.

**Comment by dobozysaurus** [comment]
@matallen New PR is in (#49); closing this one.

**Pull request closed without merging**
